apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
  namespace: tidb-cluster
spec:
  version: v6.5.0
  timezone: UTC
  pvReclaimPolicy: Delete
  enableDynamicConfiguration: true
  pd:
    replicas: 1
    config: {}
    storageClassName: openebs-hostpath
    requests:
      storage: "1Gi"
      cpu: "500m"
      memory: "512Mi"
  tidb:
    replicas: 1
    config:
      performance:
        max-procs: 4
    service:
      type: ClusterIP
    storageClassName: openebs-hostpath
    requests:
      storage: "1Gi"
      cpu: "500m"
      memory: "1Gi"
  tikv:
    replicas: 1
    config: {}
    storageClassName: openebs-hostpath
    requests:
      storage: "1Gi"
      cpu: "500m"
      memory: "1Gi"
