apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satellite-app.fullname" . }}-frontend
  labels:
    app: {{ include "satellite-app.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "satellite-app.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "satellite-app.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.frontend.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.frontend.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.frontend.tolerations | nindent 8 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "satellite-app.fullname" . }}-frontend
  labels:
    app: {{ include "satellite-app.name" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "satellite-app.name" . }}-frontend
