version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - orbitalnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - orbitalnet

networks:
  orbitalnet:
